"""fix camera time_of_day field type

Revision ID: e3022ee0b37c
Revises: 4b92598faf6a
Create Date: 2025-05-15 17:42:39.397069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3022ee0b37c'
down_revision: Union[str, None] = '4b92598faf6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'time_of_day',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=10),
               comment='Время суток: утро, день, вечер, ночь',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'time_of_day',
               existing_type=sa.String(length=10),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время суток: утро, день, вечер, ночь',
               existing_nullable=False)
    # ### end Alembic commands ###
