"""empty message

Revision ID: eff753d1b7c2
Revises: 
Create Date: 2025-05-26 11:05:51.245983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff753d1b7c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('camera_class_cd', sa.Integer(), nullable=False),
    sa.Column('camera_class', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('camera_name', sa.String(length=255), nullable=False),
    sa.Column('camera_place', sa.String(length=255), nullable=False),
    sa.Column('camera_place_cd', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('camera_type_cd', sa.Integer(), nullable=False),
    sa.Column('camera_type', sa.String(length=100), nullable=False),
    sa.Column('camera_latitude', sa.Float(), nullable=False),
    sa.Column('camera_longitude', sa.Float(), nullable=False),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('azimuth', sa.Integer(), nullable=False),
    sa.Column('process_dttm', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('video_key', sa.String(length=255), nullable=False),
    sa.Column('preview_key', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('video_resolution', sa.String(length=20), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(length=10), nullable=False, comment='Время суток: утро, день, вечер, ночь'),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('users')
    op.drop_table('cameras')
    # ### end Alembic commands ###
